extends: '@istanbuljs/nyc-config-typescript'
all: true
check-coverage: false
include:
  - src/**/*.ts
exclude:
  - node_modules
extension:
  - .ts
  - .js
  - .jsx
  - .tsx

branches: 60
lines: 80
functions: 80
statements: 80
