all: true
check-coverage: false
include:
  - lib/src
  - src
exclude:
  - node_modules
  - "**/*.d.ts"
sourceMap: true
extension:
  - .ts
  - .js
  - .jsx
  - .tsx

branches: 60
lines: 80
functions: 80
statements: 80
